<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_TEST" Id="{e7f94b3d-7e0c-0092-1dcf-e0d256598b7c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TEST
VAR
    _testSuite : TcUnitContext;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_testSuite.Run();
_testSuite.RtcSynchronize(true, '', 60);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>