<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="PRG_TEST_1" Id="{2dc1ad44-fabf-06dc-3389-3a5eaed67bf6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_TEST_1
VAR
    _testSuite : TcUnitContext;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[_testSuite.Run();
_testSuite.RtcSynchronize(true, '', 60);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>