<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TcUnitContext" Id="{dd18f4d7-6df7-4b05-803e-832112e31421}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TcUnitContext EXTENDS TcoCore.TcoContext
VAR
    testStation : TestStation(THIS^);

    {attribute addProperty Name "Versionsnummer Plc"}
    version : STRING(23);
    //~
    programVersion : ST_LibVersion;
    //~

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Main" Id="{4948e276-ecde-4c1e-90c1-dcfc1933ff78}">
      <Declaration><![CDATA[(*~
    <docu>
        <summary>
            Main method of the TcoContext. This is the entry point of any control logic that belongs to this context.
            The call of this method is ensured by calling the <c>InstanceName.Run()</c> method, and it must not be called explicitly.
            This method is abstract, and it must be overridden in derived block.
        </summary>
    </docu>
~*)
METHOD PROTECTED Main
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
testStation();
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>