//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardLibGemaConnector.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StandardLibGemaConnector.Properties.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual acceleration.
        /// </summary>
        public static string ___Actual_acceleration__ {
            get {
                return ResourceManager.GetString("___Actual_acceleration__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual modulo position.
        /// </summary>
        public static string ___Actual_modulo_position__ {
            get {
                return ResourceManager.GetString("___Actual_modulo_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual modulo turns.
        /// </summary>
        public static string ___Actual_modulo_turns__ {
            get {
                return ResourceManager.GetString("___Actual_modulo_turns__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual position in mm.
        /// </summary>
        public static string ___Actual_position_in_mm__ {
            get {
                return ResourceManager.GetString("___Actual_position_in_mm__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual torque.
        /// </summary>
        public static string ___Actual_torque__ {
            get {
                return ResourceManager.GetString("___Actual_torque__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual velocity.
        /// </summary>
        public static string ___Actual_velocity__ {
            get {
                return ResourceManager.GetString("___Actual_velocity__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschleunigung (0 - 100).
        /// </summary>
        public static string ___Beschleunigung__0___100___ {
            get {
                return ResourceManager.GetString("___Beschleunigung__0___100___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command number.
        /// </summary>
        public static string ___Command_number__ {
            get {
                return ResourceManager.GetString("___Command_number__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command state.
        /// </summary>
        public static string ___Command_state__ {
            get {
                return ResourceManager.GetString("___Command_state__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deceleration.
        /// </summary>
        public static string ___Deceleration__ {
            get {
                return ResourceManager.GetString("___Deceleration__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string ___Disabled__ {
            get {
                return ResourceManager.GetString("___Disabled__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string ___Distance__ {
            get {
                return ResourceManager.GetString("___Distance__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive error no .
        /// </summary>
        public static string ___Drive_error_no___ {
            get {
                return ResourceManager.GetString("___Drive_error_no___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable negative.
        /// </summary>
        public static string ___Enable_negative__ {
            get {
                return ResourceManager.GetString("___Enable_negative__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable positive.
        /// </summary>
        public static string ___Enable_positive__ {
            get {
                return ResourceManager.GetString("___Enable_positive__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string ___Enabled__ {
            get {
                return ResourceManager.GetString("___Enabled__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ___Error__ {
            get {
                return ResourceManager.GetString("___Error__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error id.
        /// </summary>
        public static string ___Error_id__ {
            get {
                return ResourceManager.GetString("___Error_id__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschwindigkeit in mm/s.
        /// </summary>
        public static string ___Geschwindigkeit_in_mm_s__ {
            get {
                return ResourceManager.GetString("___Geschwindigkeit_in_mm_s__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halt.
        /// </summary>
        public static string ___Halt__ {
            get {
                return ResourceManager.GetString("___Halt__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jogging.
        /// </summary>
        public static string ___Jogging__ {
            get {
                return ResourceManager.GetString("___Jogging__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string ___Mode__ {
            get {
                return ResourceManager.GetString("___Mode__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motion state.
        /// </summary>
        public static string ___Motion_state__ {
            get {
                return ResourceManager.GetString("___Motion_state__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move absolute.
        /// </summary>
        public static string ___Move_absolute__ {
            get {
                return ResourceManager.GetString("___Move_absolute__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move modulo.
        /// </summary>
        public static string ___Move_modulo__ {
            get {
                return ResourceManager.GetString("___Move_modulo__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move relative.
        /// </summary>
        public static string ___Move_relative__ {
            get {
                return ResourceManager.GetString("___Move_relative__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string ___Position__ {
            get {
                return ResourceManager.GetString("___Position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position in mm.
        /// </summary>
        public static string ___Position_in_mm__ {
            get {
                return ResourceManager.GetString("___Position_in_mm__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positionierbereich in mm.
        /// </summary>
        public static string ___Positionierbereich_in_mm__ {
            get {
                return ResourceManager.GetString("___Positionierbereich_in_mm__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power enable.
        /// </summary>
        public static string ___Power_enable__ {
            get {
                return ResourceManager.GetString("___Power_enable__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string ___Reset__ {
            get {
                return ResourceManager.GetString("___Reset__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schubstrombegrenzung.
        /// </summary>
        public static string ___Schubstrombegrenzung__ {
            get {
                return ResourceManager.GetString("___Schubstrombegrenzung__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set position.
        /// </summary>
        public static string ___Set_position__ {
            get {
                return ResourceManager.GetString("___Set_position__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string ___Stop__ {
            get {
                return ResourceManager.GetString("___Stop__", resourceCulture);
            }
        }
    }
}
